name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for submitting your first issue ! We will do our best to correct as quick as we can'' first issue'
        pr-message: 'Thanks for submitting your first pull request! All the OpenSource community is thankful to you'' first pr'
